### ISSUE TITLE
ovladani ssr

### ISSUE THREAD

**Issue by pulss** [petrleocompel/hass-wattrouter-mx#3]
Dobry den,
Integraci mam naistalovanou, vidim 8 entit, ale kdyz prepinam, tak watrouter nespina, nerozsviti se kontrolni led ani led na ssr rele, poradite prosim?
Dekuji

**Comment by petrleocompel** [comment]
O jakou verzi FW se jedná ? 

Aktuálně nejnovější verze má v sobě "modbus" která je mnohlem lepší než tato integrace. Bohužel oficální dokumentace není úplně příjemná. 

A tak bohužel integrace trochu upadla v zapomnění, protože `wattrouter` s webovým API opravdu nepracuje dobře.

**Comment by petrleocompel** [comment]
Modbus v nové verzi vypadá OK. Nahradím integraci ukázkou jak nakonfigurovat modbus.
Integrace bude označena jako `deprecated`/`discontinued` (zastaralá - ukončená)

**Comment by pulss** [comment]
Dobrý den,

fw je 2.2.1, jakou novou verzi myslite? Tuto https://github.com/yardee/ha-wattrouter ?

Ta ma jen senzory, neumim s ni spinat rele :(

PS

**Comment by petrleocompel** [comment]
Integrace nebude potřeba (HA má integraci modbus v sobě, konfiguruje se ručně přes `configuration.yaml`, https://www.home-assistant.io/integrations/modbus/ )
Ano od verze 2.2 vypadá že lze přes modbus spínat i relé.

**Comment by petrleocompel** [comment]
@pulss 
Aktuálně jsem již byl schopen nahradit integraci za modbus. 
Ukázka konfigurace pro `configuration.yaml`
```yaml

modbus:
  - name: wattrouter
    type: tcp
    host: 192.168.0.50 # IP zařízení
    port: 502
    sensors:
      - name: Wattrouter Voltage Phase 1
        unique_id: wattrouter_voltage_phase_1
        slave: 1
        address: 8
        data_type: int32
        device_class: voltage
        input_type: input
        state_class: measurement
        unit_of_measurement: "V"
      - name: power_phase_1
        unique_id: wattrouter_power_phase_1
        slave: 1
        address: 0
        data_type: int32
        count: 2
        device_class: power
        scale: 10
        input_type: input
        state_class: measurement
        unit_of_measurement: "W"
      - name: power_phase_2
        unique_id: wattrouter_power_phase_2
        slave: 1
        address: 2
        data_type: int32
        device_class: power
        scale: 10
        input_type: input
        state_class: measurement
        unit_of_measurement: "W"
      - name: power_phase_3
        unique_id: wattrouter_power_phase_3
        slave: 1
        address: 4
        data_type: int32
        device_class: power
        scale: 10
        input_type: input
        state_class: measurement
        unit_of_measurement: "W"
      - name: consumption_vt_daily
        unique_id: wattrouter_consumption_vt_daily
        slave: 1
        address: 92
        data_type: int32
        device_class: energy
        scale: 10
        input_type: input
        state_class: total_increasing
        unit_of_measurement: "Wh"
      - name: consumption_nt_daily
        unique_id: wattrouter_consumption_nt_daily
        slave: 1
        address: 94
        data_type: int32
        device_class: energy
        scale: 10
        input_type: input
        state_class: total_increasing
        unit_of_measurement: "Wh"
      - name: leftower_daily
        unique_id: wattrouter_leftower_daily
        slave: 1
        address: 96
        data_type: int32
        device_class: energy
        scale: 10
        input_type: input
        state_class: total_increasing
        unit_of_measurement: "Wh"
      - name: production_daily
        unique_id: wattrouter_production_daily
        slave: 1
        address: 98
        data_type: int32
        device_class: energy
        scale: 10
        input_type: input
        state_class: total_increasing
        unit_of_measurement: "Wh"
```

Ovládání relé nemám ještě zprovozněné ale dle dokumentace https://solarcontrols.cz/archives/eshop/WATTrouterMx_CZ.pdf
je možné. Pouze opět trochu speciální způsob spínání relé.

Další hodnoty mohou být vyčteny z registrů, nutno dopsat sensory. Stejný způsob.
